package AppKickstarter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
        import java.io.DataInputStream;
        import java.io.DataOutputStream;
        import java.io.IOException;
        import java.net.InetAddress;
        import java.net.Socket;
        import java.net.UnknownHostException;
        import java.util.logging.Level;
        import java.util.logging.Logger;
        import java.io.FileOutputStream;

/**
 *
 * @author Shiying
 */
public class Client extends javax.swing.JFrame implements Runnable {

    Socket socket;
    DataInputStream in;
    DataOutputStream out;
    static Client client;
    final String ticketReq="TicketReq: ";
    final String cidP="Client-";
    int numP;
    static int totalP;
//    static int[] ticketNum={0,0,0,0,0};

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    @Override
    public void run() {
    }

    public void connect(String serverIP, int port) throws UnknownHostException, IOException {
        socket = new Socket(InetAddress.getByName(serverIP), port);
        in = new DataInputStream(socket.getInputStream());
        out = new DataOutputStream(socket.getOutputStream());
        Thread thread = new Thread(this);
        thread.start();
    }

    byte[] receive() throws IOException {
        int len;
        int size = in.readInt();
        byte[] buffer = new byte[size];
        do {
            len = in.read(buffer, buffer.length - size, size);
            size -= len;
        } while (size > 0);
        return buffer;
    }

    void send(String msg) throws IOException {
        System.out.println(msg.length());
        out.writeInt(1024);
        out.writeBytes(msg);
        out.flush();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        usrFrame = new javax.swing.JFrame();
        alert = new javax.swing.JTextField();
        connect = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        getTicket = new javax.swing.JButton();
        nPersons = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        response = new javax.swing.JTextField();

        usrFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        usrFrame.setBounds(new java.awt.Rectangle(0, 0, 465, 400));

        alert.setEditable(false);
        alert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertActionPerformed(evt);
            }
        });

        connect.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Restaurant Queuing System: Client");

        jLabel2.setText("Please Connect to the Server!");

        javax.swing.GroupLayout usrFrameLayout = new javax.swing.GroupLayout(usrFrame.getContentPane());
        usrFrame.getContentPane().setLayout(usrFrameLayout);
        usrFrameLayout.setHorizontalGroup(
                usrFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(usrFrameLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(usrFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(usrFrameLayout.createSequentialGroup()
                                                .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(connect))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(usrFrameLayout.createSequentialGroup()
                                                .addGap(199, 199, 199)
                                                .addComponent(jLabel2)))
                                .addContainerGap(43, Short.MAX_VALUE))
        );
        usrFrameLayout.setVerticalGroup(
                usrFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(usrFrameLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(usrFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(connect))
                                .addGap(49, 49, 49))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 680, 380));

        label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label.setText("Hi, please input the number of people and get ticket.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Restaurant Queuing System: Client");

        getTicket.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getTicket.setText("Get Ticket!");
        getTicket.setActionCommand("getTicket");
        getTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTicketActionPerformed(evt);
            }
        });

        nPersons.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        nPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPersonsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Num of People:");

        response.setEditable(false);
        response.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(response, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(nPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(getTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(nPersons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(response, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            client.connect("127.0.0.1", 54321);
            client.setVisible(true);
            client.usrVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void alertActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void getTicketActionPerformed(java.awt.event.ActionEvent evt) {
        String req="";
        String numString=nPersons.getText();
        numP = Integer.parseInt(numString);
        if (numP<=10){
            totalP++;
            req=ticketReq+cidP+Integer.toString(totalP)+' '+numString;
            System.out.println("req is "+req);
            response.setText("Please Wait... "+req);
            try {
                send(req);
            } catch (IOException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            response.setText("Too many people!!!!! Number of People should be less than or equal to 10.");
        }
//        ticketReq
        // TODO add your handling code here:
    }

    private void nPersonsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void responseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void usrVisible(boolean b) {
        usrFrame.setVisible(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                client = new Client();
                client.usrVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField alert;
    private javax.swing.JButton connect;
    private javax.swing.JButton getTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label;
    private javax.swing.JTextField nPersons;
    private javax.swing.JTextField response;
    private javax.swing.JFrame usrFrame;
    // End of variables declaration
}
